### PR TITLE
V2/parameter map

### PR DESCRIPTION
**Pull request by kn0ll**
hello,

here is some implementation of a parameter map.

here is an [example map](https://github.com/catshirt/Audiolet/blob/v2/parameter-map/src/dsp/Sine.js#L22-L24)

here is the [core mapping logic](https://github.com/catshirt/Audiolet/blob/v2/parameter-map/src/core/AudioletNode.js#L38-L47)

for instance, in the case of `parameters: { frequency: [0, 440] }`, an AudioletParameter will be assigned to `node.frequency`, bound to input 0 with a default value of 440. it's important to note that the nodes `parameters` are stagnant: so parameters[1] will always access the default value, not the current value. maybe a better name than parameters is defaults?

there is one breaking change which i can't find any use of: `generate` was removed as an argument to the nodes constructor. so you must set it on the prototype now. the reason for this is i wanted to still give nodes the ability to [override parameter defaults in the constructor](https://github.com/catshirt/Audiolet/blob/v2/parameter-map/src/dsp/Sine.js#L33-L36). having generate in the arguments meant you'd always be passing `null` as an option before the parameters, and it seemed simpler to just remove it.

finally, in general, there are ways to improve this api. but this was, i found, the most straight forward. i am of course, open to all suggestions here.

### CODE REVIEW

**Comment by oampo** [comment]
Yes, this looks very nice, and a lot cleaner than the old version.  You are right about parameters being stagnant, that is a bit strange maybe.  How do you feel about overwriting the "default" parameter with the actual parameter?  I've added an inline comment to show what this would look like.

The other little issue is with using || to set the parameter value - if the default has a value but you want the parameter to be 0 then this won't work.  It was a problem in the old code which I never got round to completely fixing.  Instead it should check whether the parameter value is null or undefined, and set it otherwise.

Looking at the code, I think my version of the extends method will probably break the mapping, so let's get something sorted for that (or at least work out what the Backbone method is doing :grinning:), then get this merged.
Cheers,
Joe

**Comment by kn0ll** [comment]
if i recall correctly, i believe the reason i didn't update the default parameter was simply because that would mean updating all parameters in 2 places. which means 2 ways to access the parameter (weird, subjectively), and 2 times the writes (bad, concretely. significantly bad? unsure). i am obviously not bound to my implementation, just providing context. are these non-issues? 

i have no interest in reading into that Backbone method. :) i will simplify.

**Comment by oampo** [comment]
Yeah, I see what you mean about having two ways to access the parameter.  The thing is, I really want to keep the `sine.frequency` style of access, but for UI stuff it is much nicer to have some way of accessing the parameters programatically.  How about adding a `getParameter(name)` and `getParameterNames()` methods, and renaming `this.parameters` to something like `parameterMap`?

Doubling the writes should make almost no difference - the DSP is so much more costly that it becomes pretty much insignificant unless you are doing something really non-standard.

**Comment by kn0ll** [comment]
ok, so i've kept the stagnant parameter and instead augmented the initial parameters hash with an Audiolet node. so the work flow looks like this:
1. you declare `parameters` in your node class definition. like: `parameters: { frequency [0, 440] }`.
2. when your node is initialized, it creates an AudioletParameter for each, and adds it to the third index of the original parameter array. so after constructor is run, parameters now looks like this: `parameters: { frequency [0, 440, AudioletParameter] }`
3. `get` and `set` methods are exposed on the node to provide a simple interface for accessing parameters. you shouldn't really probably need to touch the `parameters` hash directly beyond declaration.

this implementation ensures that a) parameters are not being written in 2 places, b) there is a terse method for accessing and setting parameters, c) allows us to keep a default version of the original parameter without concern (which could come in handy).

i'm fine tuning now but this is the general idea.

**Comment by kn0ll** [comment]
> The other little issue is with using || to set the parameter value - if the default has a value but you want the parameter to be 0 then this won't work. It was a problem in the old code which I never got round to completely fixing. Instead it should check whether the parameter value is null or undefined, and set it otherwise.

i'm not sure i understand this. if i define my default parameter value as 0, this evaluation will pass in false as a value to AudioletParameter. AudioletParameter falls back to 0 when false, though. so this sounds ok to me?

> How do you feel about overwriting the "default" parameter with the actual parameter? I've added an inline comment to show what this would look like.

i actually realized during last commit that `parameters` is a class property. so keeping it as the default parameter actually makes sense, and modifying it would actually require creating an additional instance copy. with the new commits, i feel like maybe keeping `parameters` as the default, and using `get` and `set` to interact with instance values is sufficient?

**Comment by oampo** [comment]
Yeah, this looks good now I think - the setter and getter are nice, and it doesn't break backwards-compatibility.  My one hesitation is that I think having a variable called parameters which isn't just a list or map of parameters is still kind of strange - I think I'd probably prefer a variable for defaults and a variable for the actual parameters.

That said, this is still not a big issue, and if it causes problems down the line it's a simple fix so I'll merge it and see when the last issue with || is fixed.

**Comment by oampo** [comment]
On the || issue, the problem is this - say I create a node:

``` js
var MyNode = AudioletNode.extend({
    parameters: {
        value: [0, 440],
    },

   constructor: function(value) {
       AudioletNode.call(this, audiolet, 1, 1, {value: value});
});
```

Then if I try to create an instance of the node with value 0:

``` js
var myInstance = new MyNode(0);
```

The value of the parameter is given to be 0 || 440, which evaluates to 440.  This is despite the fact that we tried to create a MyNode with value 0.  Fix this and I'm happy to merge.

**Comment by kn0ll** [comment]
hi Joe,

sorry for the delay! slow and steady but- i think we're in good shape now? as the last 2 relevant commits suggest, i've:
1. added a proper existence check expecting 0 as a possible value
2. changed `parameters` to `defaults`, so that `defaults` is used only for setup
3. moved parameters from the node to `parameters` (ie. node.frequency is now node.parameters.frequency, which of course should be accessed through the setters and getters.

**Comment by oampo** [comment]
Awesome - this all looks great now.  Pulled!

**Pull request merged**
