### PR TITLE
Remove MooTools dependency

### PR DESCRIPTION
**Pull request by ekosz**
I rewrote nearly every file to use Javascript sudo-classes instead of MooTool's `Class` method. To replicate the class inheritance I used [Peter Michaux's Method](http://peter.michaux.ca/articles/class-based-inheritance-in-javascript) and added an `extend(subclass, partentclass)` method.   I also replaced MooTool's `instanceOf` method and replaced it with the native javascript `instanceof`. I also updated the example `Demo` to use the updated library and prove that it works.  Finally the test environment file was also updated and no longer has a dependence on MooTools.

I was hoping that by removing MooTools (a seemingly large library), Audiolet would seem more excisable and lightweight. Unfortunately, because Audiolet was so tied to MooTools this is a very large update, and future contributors would need to use this new method of Classes.

This is my first pull request (ever) and would be happy to make any changes people see fit.

### CODE REVIEW

**Comment by kn0ll** [comment]
pulled or not, this is awesome. was considering it myself but was intimidated by the size. kudos.

**Comment by oampo** [comment]
Okay, given that most of the work has been done and a few people have asked for it, I've started working on getting this committed.  There are a few functions other than the class system and the instanceOf method which come from MooTools, and I want to be certain that there are no regressions introduced in doing this, so I've created a new branch at https://github.com/oampo/Audiolet/tree/reviews%2Fekosz to sort everything out in.

Many thanks for the work @ekosz, it all looks great.  Will close the pull request when it gets merged, and I'll keep an eye on your branch so I can pull over any commits to the reviews/ekosz branch which you put in in the meantime.

**Comment by ekosz** [comment]
Awesome.  I also have begun to update the example files I skipped over in the first round.  For the future, how would you like the code to be formated?  I notice you use 4 space indenting, and function calls add the end of methods to be indented as well.  Is there anything else so you don't have to re-do any future commits?

**Comment by clindsey** [comment]
Awesome! Thanks, ekosz

**Comment by oampo** [comment]
@ekosz Yeah, that's basically it.  I very roughly try to follow these guidelines: http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml but I'm not super strict.  The only other thing is I try to keep lines < 80 characters, as I do most of my coding in a terminal.

**Pull request merged**
