### PR TITLE
base class

### PR DESCRIPTION
**Pull request by kn0ll**
hi,

as discussed, this is the base class implementation. at the moment this primarily only exposes an empty function with a single "extend" function. this allows you to use an object API, with prototypal inheritance.

i copied the extend function from Backbone, just for its maturity. to be 100% honest i'm not sure of the implications here, or if we should simplify it to something like the existing extend function.

there is a breaking change introduced from v1: the original `extend` function has been removed from Audiolet. although the previous extend function will continue to work fine on these new Audiolet classes, if that is what someone would prefer, they will have to BYO extend.

### CODE REVIEW

**Comment by oampo** [comment]
Hey Nic,
This all looks good, but I'd quite like to sort out a simpler extend function (mainly because I can't make head nor tail of what the Backbone one is doing...).  I think that this is the equivalent to the Backbone method using the same technique as the Peter Michaux one that Audiolet was using before:

``` js
AudioletClass.extend = function(object) {
    function Dummy() {}
    Dummy.prototype = this.prototype;
    var subclass = object["constructor"] ? object["constructor"] : function() {}
    subclass.prototype = new Dummy();
    for (var key in object) {
        if (object.hasOwnProperty(key)) {
            subclass.prototype[key] = object[key];
        }
    }
    subclass.extend = this.extend;
    return subclass;
};
```

Does this look okay at your end, and can you give it a quick test to make sure it works like I think it does - I've written it pretty quickly, so it may be slightly borked somewhere!  If it looks okay, can you make that change and then I'm happy to merge this.

Cheers,
Joe

**Comment by kn0ll** [comment]
sound good. i broke my own rule of simple. i will get to it this weekend.

in the mean time i opened up a pull review for [parameter map](https://github.com/oampo/Audiolet/pull/43). this requires (and actually contains, at the moment) commits from the base class branch, so it should probably be merged in that order. just opening for your reference now until i can wrap this one up. thanks

**Comment by kn0ll** [comment]
sorry for the delay.

i realized when i finally looked at it that the Backbone implementation is almost identical to what you proposed, with some sugar on top (static properties, super access). i removed these and the wrapper function and ended up with something much closer to what you had in your comment.

i also realized during this pass that the Backbone extend method is probably almost identical to the coffeescript extend method, and using coffeescript would eliminate the need for a defined extends function all together.

that all aside, i think this is proper now.

**Comment by oampo** [comment]
Awesome - yeah, that's much easier to understand.  Consider it merged!
Joe

**Pull request merged**
